feat: Allure-results

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -15,9 +15,17 @@ jobs:
     steps:
       # Шаг 1: Клонирование репозитория
       - name: Checkout repository
-        uses: actions/checkout@v2
+        uses: actions/checkout@v3
 
-      # Шаг 2: Установка Allure
+      # Шаг 2: Проверка наличия результатов Allure
+      - name: Check Allure Results Exist
+        run: |
+          if [ ! -d "./allure-results" ]; then
+            echo "Allure results not found!"
+            exit 1
+          fi
+
+      # Шаг 3: Установка Allure
       - name: Install Allure Commandline
         run: |
           wget https://github.com/allure-framework/allure2/releases/download/2.18.1/allure-2.18.1.tgz
@@ -25,20 +33,20 @@ jobs:
           sudo mv allure-2.18.1 /opt/allure
           export PATH=$PATH:/opt/allure/bin
 
-      # Шаг 3: Генерация однофайлового отчета (index.html)
+      # Шаг 4: Генерация однофайлового отчета (index.html)
       - name: Convert Allure Report to Single HTML
         run: |
          allure generate -c --single-file ./allure-results -o ./allure-report-html
 
 
-      # Шаг 4:  Загрузка однофайлового отчета как артефакт
+      # Шаг 5:  Загрузка однофайлового отчета как артефакт
       - name:  Upload Single HTML Report
         uses: actions/upload-artifact@v3
         with:
           name: allure-report-html
           path: ./allure-report-html
 
-      # Шаг 5: Публикация отчета на GitHub Pages
+      # Шаг 6: Публикация отчета на GitHub Pages
       - name: Deploy Allure Report to GitHub Pages
         uses: peaceiris/actions-gh-pages@v3
         with:
